# Generated by Django 5.0.5 on 2024-10-26 16:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'user аgreement',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'Privacy policy',
            },
        ),
    ]
