# Generated by Django 5.0.5 on 2024-11-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementmodel',
            options={'verbose_name': 'Пользовательское соглашение', 'verbose_name_plural': 'Пользовательское соглашение'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicymodel',
            options={'verbose_name': 'Политика конфидициальности', 'verbose_name_plural': 'Политика конфидициальности'},
        ),
    ]
