# Generated by Django 5.0.5 on 2024-09-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница')], max_length=10, verbose_name='день проведения')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('end_time', models.TimeField(verbose_name='конец')),
                ('capacity', models.PositiveIntegerField(verbose_name='размер группы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'Групповое занятие',
                'verbose_name_plural': 'Групповые занятия',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('sur_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('contact', models.CharField(max_length=100, verbose_name='контактные данные')),
                ('text', models.TextField(verbose_name='текст')),
                ('agree_to_privacy_policy', models.BooleanField(default=False, verbose_name='согласен на обработку персональных данных')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='получен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.grouplesson')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='WantWriteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('contact', models.CharField(max_length=100, verbose_name='контактные данные')),
                ('agree_to_privacy_policy', models.BooleanField(default=False, verbose_name='согласен на обработку персональных данных')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='получен')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grouplesson', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'Желающий записаться в группу',
                'verbose_name_plural': 'Желающие записаться в группу',
                'ordering': ['-created'],
            },
        ),
    ]
