# Generated by Django 5.0.5 on 2024-09-16 07:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание'),
        ),
    ]
