# Generated by Django 5.0.5 on 2024-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_grouplesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='city',
            field=models.CharField(default='неизвестен', verbose_name='город проведения'),
        ),
        migrations.AddField(
            model_name='grouplesson',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽'), ('BYN', 'Br')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='grouplesson',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
