# Generated by Django 5.0.5 on 2024-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_grouplesson_city_grouplesson_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('₽', 'RUB'), ('Br', 'BYN')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
    ]
