# Generated by Django 5.0.5 on 2024-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_grouplesson_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('₽', 'RUB'), ('Br', 'BYN')], default='€', max_length=3, verbose_name='Валюта'),
        ),
    ]
