# Generated by Django 5.0.5 on 2024-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_grouplesson_show_if_no_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='on_time_event',
            field=models.BooleanField(default=False, verbose_name='разовое занятие'),
        ),
    ]
