# Generated by Django 5.0.5 on 2024-09-03 12:03

import ckeditor.fields
import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=news.models.path_media_file, verbose_name='Картинка')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('description', ckeditor.fields.RichTextField(default='', verbose_name='Описание')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cоздана')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('agree_to_privacy_policy', models.BooleanField(default=False, verbose_name='согласен на обработку персональных данных')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='подписан')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsmodel')),
            ],
            options={
                'unique_together': {('news', 'ip_address')},
            },
        ),
    ]
