# Generated by Django 5.0.5 on 2024-09-03 14:20

import django.core.validators
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='file',
            field=models.FileField(blank=True, upload_to=news.models.path_media_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi'])], verbose_name='загрузить файл'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], default='photo', max_length=10),
        ),
    ]
