# Generated by Django 5.0.5 on 2024-11-10 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='iframe_code',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='HTML код iframe video'),
        ),
    ]
